<a href="https://colab.research.google.com/github/abishekP101/Pytorch/blob/main/PytorchLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

print(torch.__version__)

2.8.0+cu126


## Creating Tensors

In [2]:
a = torch.empty(2 ,3)
a

tensor([[2.3077e+34, 4.4229e-41, 2.3077e+34],
        [4.4229e-41, 1.6396e-38, 0.0000e+00]])

In [4]:
b = torch.zeros(3 ,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
c = torch.ones(2,1)
c

tensor([[1.],
        [1.]])

In [6]:
d = torch.rand(3,3)
d

tensor([[0.1969, 0.6694, 0.3955],
        [0.3031, 0.8121, 0.4780],
        [0.4386, 0.4104, 0.2208]])

In [7]:
torch.manual_seed(100)
torch.rand(3,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [8]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
torch.arange(0 , 10 , 2)

tensor([0, 2, 4, 6, 8])

In [11]:
torch.linspace(0 , 10 , 5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [12]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
torch.full((3,3) ,5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

## Tensor shapes

In [15]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[          827338672,           828038992,   72340172838076673],
        [7308604897285731073,                  48,                  48]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])